import {test , expect} from '@playwright/test';
import {LoginPage} from '../pages/login.js';
import path from 'path';
function getTodayDayNumberString() {
    const today = new Date();
    // Use getDate() to get the day of the month (1-31)
    return String(today.getDate());
}

test('MSP Provide Login Test Suite', async ({page}) => {
    const loginPage = new LoginPage(page);
    await loginPage.gotoLoginPage();
    await loginPage.login('GCC1@vmailsink.dmm.vodafone.com','digicom123');
    await page.getByRole('tab', { name: 'Order Submission' }).click();
    await page.getByText('Create').first().click();
    await page.locator('input[name="fcxGenInfoForm.fcxGenInfoFS.2c2a9138-845b-4005-84bc-8c6ef057048a"]').click();
    await page.locator('input[name="fcxGenInfoForm.fcxGenInfoFS.2c2a9138-845b-4005-84bc-8c6ef057048a"]').fill('spyder');
    await page.getByRole('heading', { name: 'SPYDER TECH 2' }).click();
    await page.getByLabel('', { exact: true }).first().click();
    await page.getByLabel('9557348').click();
    await page.getByLabel('', { exact: true }).first().click();
    await page.getByRole('option', { name: 'MSP NNI' }).click();
    const todayDayNumber3 = getTodayDayNumberString(); // This will return '22' 
    await page.getByRole('button', { name: 'Choose date' }).click();
    await page.getByRole('gridcell', { name: todayDayNumber3 }).click();
    await page.locator('[id="mui-component-select-fcxGenInfoForm.fcxGenInfoFS.bf1482ae-4c90-4320-ae29-f1215508bbef"]').click();
    await page.getByLabel('VBI - Carrier').click();
    await page.locator('input[name="fcxGenInfoForm.fcxGenInfoFS.bc61fe7a-ccf3-4557-9584-042a0f3742f2"]').click();
    await page.locator('input[name="fcxGenInfoForm.fcxGenInfoFS.bc61fe7a-ccf3-4557-9584-042a0f3742f2"]').fill('Ashok');
    await page.getByLabel('', { exact: true }).click();
    await page.getByLabel('Afghanistan').click();
    await page.locator('input[name="fcxGenInfoContactForm.fcxCustContactFS.2f8494bd-7f0a-41a1-9d1a-7ba09f85ab94"]').pressSequentially('GCC1');
    await page.locator('input[name="fcxGenInfoContactForm.fcxCustContactFS.5113d276-5bf3-4b12-ab8c-e304d50dd177"]').fill('GCC1@vmailsink.dmm.vodafone.com');
    await page.locator('input[name="fcxGenInfoContactForm.fcxCustContactFS.8c0efcda-ee87-450b-a7c0-959e041da3fd"]').fill('0989876532');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFAccManagerContactFS.b40f7479-e098-48c7-bf2b-d8fae3b1cd92"]').click();
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFAccManagerContactFS.b40f7479-e098-48c7-bf2b-d8fae3b1cd92"]').pressSequentially('Vodafone Manager');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFAccManagerContactFS.2b8814ce-4516-43be-85e7-ead5e63c6bbf"]').fill('GCC-M1@vmailsink.dmm.vodafone.com');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFAccManagerContactFS.c11f1845-cf6b-4759-b5ae-3b174da2aac5"]').fill('0987654561');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFTechicalContactFS.e4eb9442-1e36-4a19-9b8d-ca9b479f06e8"]').click();
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFTechicalContactFS.e4eb9442-1e36-4a19-9b8d-ca9b479f06e8"]').pressSequentially('CDC');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFTechicalContactFS.1a09da6c-6db2-4f07-9644-4110d252ffb6"]').fill('CDC1@vmailsink.dmm.vodafone.com');
    await page.locator('input[name="fcxGenInfoContactForm.fcxVFTechicalContactFS.ce8d4bd9-4d47-44bf-96b0-8bd522153789"]').fill('09876876543');
    await page.getByRole('button', { name: 'Proceed to Site & Service' }).click();    
    await page.getByRole('button', { name: 'Add New Site' }).click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.9510db92-4c3c-42e9-9c67-b3e71beb5fbe"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.9510db92-4c3c-42e9-9c67-b3e71beb5fbe"]').fill('SITENAME');
    await page.getByLabel('', { exact: true }).click();
    await page.getByRole('option', { name: 'Afghanistan' }).click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.10d23b6d-4372-46a0-9fc8-72ee1e5ae9e0"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.10d23b6d-4372-46a0-9fc8-72ee1e5ae9e0"]').fill('Afghan');
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.0c62b9a3-f677-424f-8e4c-f711e85463d7"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.0c62b9a3-f677-424f-8e4c-f711e85463d7"]').fill('Istan');
    await page.locator('div:nth-child(8) > span > .MuiFormControl-root > .MuiInputBase-root').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.fc406348-98f9-4cf2-b91b-5f4a55bb85d2"]').fill('Afga');
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.6b6a269b-40bc-4068-9880-a6421aae2fea"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.6b6a269b-40bc-4068-9880-a6421aae2fea"]').fill('stan');
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.e43ff72f-0917-4c69-b689-f0d12e5650dd"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteFS.e43ff72f-0917-4c69-b689-f0d12e5650dd"]').fill('33');
    await page.locator('input[name="fcxSiteForm.fcxSiteContactFS.1b31fe73-37f3-4941-bef7-7db537c65b77"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteContactFS.1b31fe73-37f3-4941-bef7-7db537c65b77"]').fill('Ashok');
    await page.locator('input[name="fcxSiteForm.fcxSiteContactFS.b39a0514-1557-4ca1-ac05-1fbc7ef0447b"]').click();
    await page.locator('input[name="fcxSiteForm.fcxSiteContactFS.b39a0514-1557-4ca1-ac05-1fbc7ef0447b"]').fill('ashok@gmail.com');
    await page.locator('input[name="fcxSiteForm.fcxSiteContactFS.0968aa37-872a-4339-9014-cae05b8bcfc1"]').fill('0987656543');
    await page.getByRole('button', { name: 'Add Site' }).click();
    await page.getByRole('button', { name: 'Proceed to Conf. Service' }).click();
    await page.getByRole('img', { name: 'Edit Service' }).click();
    const todayDayNumber2 = getTodayDayNumberString(); // This will return '22' 
    await page.getByRole('button', { name: 'Choose date' }).click();
    await page.getByRole('gridcell', { name: todayDayNumber2 }).click();
    await page.waitForTimeout(1000);
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.0f384d0d-7d26-465a-b720-dd10e9f0c442"]').click();
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.0f384d0d-7d26-465a-b720-dd10e9f0c442"]').fill('20250929122441-8');
    await page.locator('[id="mui-component-select-fcxMSPNNIForm.fcxMSPNNIFS.f8327e69-6378-4913-a487-7fb6b7b4d162"]').click();
    await page.getByRole('option', { name: '100M' }).click();
    await page.locator('[id="mui-component-select-fcxMSPNNIForm.fcxMSPNNIFS.33469b4f-ae8b-4de0-9077-716da870d68a"]').click();
    await page.getByLabel('Multi Mode Fiber Lx/LC').click();
    await page.getByLabel('', { exact: true }).first().click();
    await page.getByLabel('Abu Dhabi (AUHN01)').click();
    await page.getByLabel('', { exact: true }).first().click();
    await page.getByRole('option', { name: 'No' }).click();
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.fafd05f6-21a4-4bf1-8569-8d0f0ffc05a4"]').click();
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.fafd05f6-21a4-4bf1-8569-8d0f0ffc05a4"]').fill('2');
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.8a5dec74-e0e1-46dc-be79-2147178cf81d"]').click();
    await page.locator('input[name="fcxMSPNNIForm.fcxMSPNNIFS.8a5dec74-e0e1-46dc-be79-2147178cf81d"]').fill('4');
    await page.getByLabel('', { exact: true }).click();
    await page.getByLabel('Cabinet').click();
    await page.getByRole('button', { name: 'Proceed to Cost and Pricing' }).click();
    await page.locator('input[name="fcxMSPNNICustomerPricingForm.fcxMSPNNIServiceCostFS.ebce7ee4-a55b-4d87-a360-9007eb09723c"]').click();
    await page.locator('input[name="fcxMSPNNICustomerPricingForm.fcxMSPNNIServiceCostFS.ebce7ee4-a55b-4d87-a360-9007eb09723c"]').fill('12');
    await page.locator('input[name="fcxMSPNNICustomerPricingForm.fcxMSPNNIServiceCostFS.f59f7d92-0874-4c0f-a5a8-fdfe8065b2ae"]').click();
    await page.locator('input[name="fcxMSPNNICustomerPricingForm.fcxMSPNNIServiceCostFS.f59f7d92-0874-4c0f-a5a8-fdfe8065b2ae"]').fill('22');
    await page.getByRole('button', { name: 'Finish Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Attachment' }).click();
    await page.locator('.MuiBox-root.css-1nef12g').first().click();
    await page.locator('input[name="quoteReference"]').click();
    await page.locator('input[name="quoteReference"]').fill('Vodafone');
    const todayDayNumber = getTodayDayNumberString(); // This will return '22' 
    await page.getByRole('button', { name: 'Choose date' }).click();
    await page.getByRole('gridcell', { name: todayDayNumber }).click();
    const fileToUpload = path.join(__dirname, 'Doc/mm.pdf');
    const fileInputElement = page.locator('input[type="file"]');
    await fileInputElement.setInputFiles(fileToUpload);
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('img', { name: 'UploadIcon' }).click();
    const file2Selector = 'Doc/nn.pdf'; // <-- Verify this selector in the browser!
    const file2ToUpload = path.join(__dirname, file2Selector);
    const file2InputElement = page.locator('input[type="file"]');
    await file2InputElement.setInputFiles(file2ToUpload);
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('button', { name: 'Submit Order' }).click();
    await page.getByRole('button', { name: 'Copy Order ID & Close' }).click();  
    await page.getByRole('tab', { name: 'Order Validation' }).click();
    await page.getByRole('button', { name: 'All Orders' }).click();
    await page.waitForTimeout(5000);
    await page.getByRole('textbox', { name: 'search' }).click();
    await page.getByRole('textbox', { name: 'search' }).press('Control+V');
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'Self-Assign' }).click();
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'Edit' }).click();
    await page.getByRole('button', { name: 'Accept Order Header' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByRole('button', { name: 'Proceed to Site & Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Conf. Service' }).click();
    await page.getByRole('img', { name: 'Initiate Referral' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Proceed to Site & Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Conf. Service' }).click();
    await page.getByRole('img', { name: 'View Service' }).click();
    await page.getByRole('img', { name: 'EditIcon' }).nth(2).click();
    await page.getByRole('button', { name: 'Proceed to Cost and Pricing' }).click();
    await page.getByRole('button', { name: 'Finish Service' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Proceed to Attachment' }).click();
    await page.getByRole('region').getByRole('button', { name: 'Submit Referral' }).click();
    await page.waitForTimeout(3000);
    await page.getByLabel('', { exact: true }).click();
    await page.getByLabel('#Note: Carrier Quote expired - 30 days (no Clearing)').click();
    await page.locator('textarea[name="fcxSubmitReferralSummaryForm.fcxSubmitReferralSummaryFS.98a67041-c369-460c-988a-df2c7a50a571"]').click();
    await page.locator('textarea[name="fcxSubmitReferralSummaryForm.fcxSubmitReferralSummaryFS.98a67041-c369-460c-988a-df2c7a50a571"]').fill('Accept');
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('tab', { name: 'Order Submission' }).click();
    await page.getByRole('button', { name: 'Referrals' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('textbox', { name: 'search' }).click();
    await page.getByRole('textbox', { name: 'search' }).press('Control+V');
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'Chat' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('img', { name: 'close' }).click();
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.waitForTimeout(3000);
    await page.getByRole('menuitem', { name: 'Respond' }).click();
    await page.getByRole('button', { name: 'Proceed to Site & Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Conf. Service' }).click();
    await page.getByRole('img', { name: 'Edit Service' }).click();
    await page.getByRole('button', { name: '100M' }).click();
    await page.getByRole('option', { name: '1G' }).click();
    await page.getByRole('button', { name: 'Proceed to Cost and Pricing' }).click();
    await page.getByText('Back to Service Finish Service').click();
    await page.getByRole('button', { name: 'Finish Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Attachment' }).click();
    await page.getByRole('region').getByRole('button', { name: 'Submit Response' }).click();
    await page.getByRole('button', { name: 'Proceed Anyway' }).click();
    await page.getByText('Saved SuccessfullyResponse').click();
    await page.getByRole('img').nth(1).click();
    await page.getByRole('tab', { name: 'Order Validation' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Referrals' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('textbox', { name: 'search' }).click();
    await page.getByRole('textbox', { name: 'search' }).press('Control+V');
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'Chat' }).click();
    await page.getByRole('img', { name: 'close' }).click();
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'View Referral' }).click();
    await page.getByRole('button', { name: 'Action' }).click();
    await page.getByRole('button', { name: 'Update Order and Close' }).click();
    await page.locator('.MuiBox-root.css-0 > svg > path').click();
    await page.getByRole('textbox', { name: 'search' }).press('Control+V');
    await page.waitForTimeout(3000);
    await page.getByTestId('menu-opener-button').click();
    await page.getByRole('menuitem', { name: 'Edit' }).click();
    await page.getByRole('button', { name: 'Proceed to Site & Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Conf. Service' }).click();
    await page.getByRole('img', { name: 'Edit Service' }).click();
    await page.getByRole('button', { name: 'Proceed to Service Enrich Info' }).click();
    await page.getByRole('button', { name: 'Open' }).click();
    await page.getByRole('option', { name: 'AD Khan ad.khan@vodafone.com' }).click();
    await page.locator('[id="mui-component-select-fcxServiceInfoEnrichForm.fcxServiceInfoEnrichFS.b74dbe08-2312-41f1-8f5d-518d4acfcd9e"]').click();
    await page.getByLabel('Cease Team').click();
    await page.getByRole('button', { name: 'Proceed to PO Info' }).click();
    await page.getByRole('button', { name: 'Proceed to Cost and Pricing' }).click();
    await page.getByRole('button', { name: 'Finish Service' }).click();
    await page.getByRole('img', { name: 'Mark as Validated' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('button', { name: 'Close' }).click();
    await page.waitForTimeout(3000);
    await page.getByRole('img', { name: 'Accept Service' }).click();
    await page.getByRole('img', { name: 'Amend' }).click();
    await page.getByRole('button', { name: 'Proceed to Service Enrich Info' }).click();
    await page.getByRole('button', { name: 'Choose date' }).click();
    const todayDayNumber1 = getTodayDayNumberString(); // This will return '22' 
    await page.getByRole('button', { name: 'Choose date' }).click();
    await page.getByRole('gridcell', { name: todayDayNumber1 }).click();
    await page.getByLabel('', { exact: true }).first().click();
    await page.getByRole('option', { name: 'SOM' }).click();
    await page.locator('input[name="fcxServiceInfoEnrichForm.fcxServiceInfoEnrichFS.3d5f5209-feeb-49c7-b437-956f7c343a1d"]').click();
    await page.locator('input[name="fcxServiceInfoEnrichForm.fcxServiceInfoEnrichFS.3d5f5209-feeb-49c7-b437-956f7c343a1d"]').fill('Accept');
    await page.getByRole('button', { name: 'Proceed to PO Info' }).click();
    await page.getByRole('button', { name: 'Proceed to Cost and Pricing' }).click();
    await page.getByRole('button', { name: 'Finish Amendment' }).click();
    await page.getByRole('button', { name: 'Close' }).click();
        
});